on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: tariciwa@gmail.com # replace me
        MAX_DAYS: 365
        MIN_COMMITS_PER_DAY: 6
        MAX_COMMITS_PER_DAY: 10
        START_DATE: 2024-01-01  # Ganti dengan tanggal awal sesuai tahun yang diinginkan
        END_DATE: 2024-12-31    # Ganti dengan tanggal akhir sesuai tahun yang diinginkan
